# Your Solution
version: '3.8'

services:
  book_catalog:
    build:
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book_catalog
    ports:
      - "8000:80"
    environment:
      - DATABASE_URL=postgresql://benpostgresql_uyir_user:BTtPYaTuwoQgjUo1FQap4zzypwfCDPfP@dpg-crhpe4rv2p9s73be21j0-a.oregon-postgres.render.com/benpostgresql_uyir

  inventory_management:
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory_management
    ports:
      - "8001:80"
    environment:
      - DATABASE_URL=postgresql://benpostgresql_uyir_user:BTtPYaTuwoQgjUo1FQap4zzypwfCDPfP@dpg-crhpe4rv2p9s73be21j0-a.oregon-postgres.render.com/benpostgresql_uyir